create table BIKE_TB(
	ADD_GU VARCHAR(4000),
	CONTENT_ID INT primary key,
	CONTENT_NM VARCHAR(4000),
	NEW_ADDR VARCHAR(4000),
	CRADLE_COUNT INT,
	LOGINTUDE INT,
	LATITUDE INT
);

select * from bike_tb ;
